import { GstType, TaxMode } from "./constants";
import { Invoice, InvoiceItem } from "./types";

export const mockInvoiceItems: InvoiceItem[] = [
  {
    id: "ii-1",
    itemId: "item-101",
    name: "Dyed Silk Fabric - Royal Blue",
    invoiceId: "inv-1",
    quantity: 120,
    basePrice: 85,
    hsnCode: 0,
    unit: "Meter",
    gstPercentage: 0,
  },
  {
    id: "ii-2",
    itemId: "item-102",
    name: "Printed Rayon Fabric - Floral",
    invoiceId: "inv-1",
    quantity: 60,
    basePrice: 140,
    hsnCode: 0,
    unit: "Meter",
    gstPercentage: 0,
  },
  {
    id: "ii-3",
    itemId: "item-103",
    invoiceId: "inv-2",
    quantity: 200,
    basePrice: 55,
    hsnCode: 0,
    unit: "Kg",
    gstPercentage: 0,
    name: "Cotton Yarn 30s",
  },
  {
    id: "ii-4",
    itemId: "item-104",
    invoiceId: "inv-3",
    quantity: 90,
    basePrice: 210,
    hsnCode: 0,
    unit: "Meter",
    gstPercentage: 0,
    name: "Embroidered Silk Fabric - Maroon",
  },
  {
    id: "ii-5",
    itemId: "item-105",
    invoiceId: "inv-4",
    quantity: 150,
    basePrice: 95,
    hsnCode: 0,
    unit: "Cones",
    gstPercentage: 0,
    name: "Polyester Sewing Thread - 40s",
  },
  {
    id: "ii-6",
    itemId: "item-106",
    invoiceId: "inv-4",
    quantity: 80,
    basePrice: 160,
    hsnCode: 0,
    unit: "Meter",
    gstPercentage: 0,
    name: "Mulberry Silk Lining Fabric",
  },
  {
    id: "ii-7",
    itemId: "item-107",
    invoiceId: "inv-5",
    quantity: 75,
    basePrice: 320,
    hsnCode: 0,
    unit: "Meter",
    gstPercentage: 0,
    name: "Premium Cotton Blend Fabric",
  },
  {
    id: "ii-8",
    itemId: "item-108",
    invoiceId: "inv-5",
    quantity: 40,
    basePrice: 180,
    hsnCode: 0,
    unit: "Pack",
    gstPercentage: 0,
    name: "Thread Cones Assorted Pack",
  },
  {
    id: "ii-9",
    itemId: "item-109",
    invoiceId: "inv-6",
    quantity: 36,
    basePrice: 280,
    hsnCode: 0,
    unit: "Set",
    gstPercentage: 0,
    name: "Sample Swatch Set",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: "INV-2025-001",
    buyerId: "party-1",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-05",
    invoiceDueDate: "2025-01-20",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-1"),
    subtotal: 18600,
    gstType: GstType.GST_18,
    taxMode: TaxMode.CGST_SGST,
    sgst: 1674,
    cgst: 1674,
    igst: 0,
    total: 21948,
    status: "DRAFT",
  },
  {
    id: 2,
    invoiceNumber: "INV-2025-002",
    buyerId: "party-1",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-12",
    invoiceDueDate: "2025-01-27",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-2"),
    subtotal: 11000,
    gstType: GstType.GST_12,
    taxMode: TaxMode.CGST_SGST,
    sgst: 660,
    cgst: 660,
    igst: 0,
    total: 12320,
    status: "PAID",
  },
  {
    id: 3,
    invoiceNumber: "INV-2025-003",
    buyerId: "party-2",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-18",
    invoiceDueDate: "2025-02-02",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-3"),
    subtotal: 18900,
    gstType: GstType.GST_18,
    taxMode: TaxMode.CGST_SGST,
    sgst: 1701,
    cgst: 1701,
    igst: 0,
    total: 22302,
    status: "OVERDUE",
  },
  {
    id: 4,
    invoiceNumber: "INV-2025-004",
    buyerId: "party-3",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-22",
    invoiceDueDate: "2025-02-06",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-4"),
    subtotal: 27050,
    gstType: GstType.GST_5,
    taxMode: TaxMode.IGST,
    sgst: 0,
    cgst: 0,
    igst: 1352.5,
    total: 28403,
    status: "ACCEPTED",
  },
  {
    id: 5,
    invoiceNumber: "INV-2025-005",
    buyerId: "party-4",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-26",
    invoiceDueDate: "2025-02-10",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-5"),
    subtotal: 31200,
    gstType: GstType.GST_5,
    taxMode: TaxMode.CGST_SGST,
    sgst: 780,
    cgst: 780,
    igst: 0,
    total: 32760,
    status: "DRAFT",
  },
  {
    id: 6,
    invoiceNumber: "INV-2025-006",
    buyerId: "party-5",
    sellerId: "seller-1",
    financialYear: "FY2025-2026",
    invoiceDate: "2025-01-30",
    invoiceDueDate: "2025-02-14",
    items: mockInvoiceItems.filter((i) => i.invoiceId === "inv-6"),
    subtotal: 10080,
    gstType: GstType.NO_GST,
    sgst: 0,
    cgst: 0,
    igst: 0,
    total: 10080,
    status: "REJECTED",
  },
];
